services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"

  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo_data:/data/db
    ports:
      - "${MONGO_PORT}:27017"

  web:
    build: .
    restart: unless-stopped
    command: 
    - bash
    - -lc
    - |
      python manage.py makemigrations accounts && python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_data:/app/staticfiles
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - mongodb

volumes:
  mysql_data:
  mongo_data:
  static_data:
