# Generated by Django 5.1.7 on 2025-04-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
