# Generated by Django 5.1.7 on 2025-05-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_contact_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(blank=True, help_text='Nomor telepon user (misalnya +6281234567890)', max_length=15, null=True, unique=True),
        ),
    ]
