# Generated by Django 5.1.7 on 2025-05-25 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_phonenumber'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('user', 'contact')},
        ),
    ]
