# Generated by Django 5.1.7 on 2025-03-09 10:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingdata',
            name='user',
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='user_id',
            field=models.IntegerField(blank=True, help_text='ID user dari database MySQL', null=True),
        ),
        migrations.AlterField(
            model_name='trackingdata',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Waktu data diterima'),
        ),
    ]
