# Generated by Django 5.1.7 on 2025-03-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_remove_trackingdata_user_trackingdata_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingdata',
            name='timestamp',
            field=models.DateTimeField(blank=True, help_text='Waktu data diterima', null=True),
        ),
    ]
