# Generated by Django 5.1.7 on 2025-04-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_iotdevice_delete_trackingdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdevice',
            name='device_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='ephemeral_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
